DROP TABLE IF EXISTS `ct_article_article`;
DROP TABLE IF EXISTS `ct_article_attribute`;
DROP TABLE IF EXISTS `ct_article_base`;
DROP TABLE IF EXISTS `ct_article_category`;
DROP TABLE IF EXISTS `ct_article_type`;
DROP TABLE IF EXISTS `ct_article_slider`;
DROP TABLE IF EXISTS `ct_article_notice`;
DROP TABLE IF EXISTS `ct_article_footnav`;
DROP TABLE IF EXISTS `ct_article_friendly_link`;
